# 1. Create a 3x3x3 array with random values 

In [3]:
import numpy as np
x= np.random.uniform((3,3,3))
print(x)

[2.44469454 2.72264709 2.03498021]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [6]:
z =np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [7]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [8]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.         0.28765437 0.89048872 0.95652396 0.41849635]
 [0.70183565 0.41289535 0.22999144 1.         0.11122898]
 [0.56784903 0.31340858 0.94824292 0.15099172 0.08542893]
 [0.47166721 0.68345465 0.83944795 0.31280387 0.09580294]
 [0.74246106 0.82925671 0.39346064 0.08331158 0.71129363]]


# 5.  How to find common values between two arrays?

In [9]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [10]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yesterday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [11]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 0 1 0 0 0]
Second array:
[0 1 0 0 1 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [12]:
import numpy as np
x = np.random.random(15)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.4768211  0.04774855 0.15079996 0.36060008 0.00852663 0.98573702
 0.58425266 0.13857372 0.1736918  0.80874967 0.4636499  0.94344808
 0.8233449  0.27111223 0.26562266]
Maximum value replaced by 0:
[0.4768211  0.04774855 0.15079996 0.36060008 0.00852663 0.
 0.58425266 0.13857372 0.1736918  0.80874967 0.4636499  0.94344808
 0.8233449  0.27111223 0.26562266]


# 9. How to print all the values of an array?

In [14]:
import numpy as np
np.set_printoptions(threshold=np.nan)
b = np.zeros((4, 4))
print(b)

ValueError: ignored

# 10.Subtract the mean of each row of a matrix

In [19]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.31479499 0.10110215 0.29993615 0.67933835 0.2466752  0.14885417
  0.95153956 0.77311666 0.45539012 0.32609241]
 [0.71518076 0.03019415 0.04861121 0.17821356 0.67211766 0.73057884
  0.43237764 0.59270634 0.44993408 0.40514004]
 [0.58040242 0.71986436 0.00521271 0.8971256  0.26799591 0.94809515
  0.71805101 0.98273994 0.14345082 0.61511135]
 [0.82235115 0.92889777 0.20188881 0.40768879 0.47116673 0.39969394
  0.5851991  0.27652097 0.14843449 0.28698062]
 [0.2122843  0.43399159 0.3228407  0.60826519 0.9735514  0.70940342
  0.57203513 0.311789   0.38430688 0.01520204]]

Subtract the mean of each row of the said matrix:

[[-0.11488898 -0.32858183 -0.12974783  0.24965437 -0.18300877 -0.28082981
   0.52185558  0.34343268  0.02570615 -0.10359156]
 [ 0.28967533 -0.39531128 -0.37689421 -0.24729187  0.24661223  0.30507342
   0.00687222  0.16720091  0.02442865 -0.02036538]
 [-0.0074025   0.13205943 -0.58259222  0.30932067 -0.31980901  0.36029023
   0.13024608  0.39493501 -0.4

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

In [17]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
#Slow version

np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([117,  57,  12])

# 13.How to find the most frequent value in an array?

In [15]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[2 4 8 0 9 9 6 0 5 4 7 8 4 2 4 1 6 0 6 4 0 9 6 5 4 2 0 8 2 7 2 5 3 4 1 8 5
 4 3 4 9 1 1 4 1 8 9 6 8 0]
rank: 4


# 14.How to get the n largest values of an array

In [16]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9996 9997 9995]


# 15.How to create a record array from a regular array?

In [18]:
import numpy as np
arra1 = np.array([("Yasemin Rayner", 88.5, 90),
                 ("Ayaana Mcnamara", 87, 99),
             ("Jody Preece", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Yasemin Rayner' '88.5' '90']
 ['Ayaana Mcnamara' '87' '99']
 ['Jody Preece' '85.5' '91']]

Record array;
[(b'Yasemin Rayner', 88.5, 90) (b'Ayaana Mcnamara', 87. , 99)
 (b'Jody Preece', 85.5, 91)]
